import React, { useMemo, useState } from 'react';
import { Activity, AlertCircle, BarChart3, Brain, CalendarDays, CheckCircle2, Database, Gauge, HeartPulse, ShieldCheck, Thermometer } from 'lucide-react';
import { Language, TelemetryReading } from '../types';
import { translations } from '../i18n/translations';
import { LoadingState } from '../components/LoadingState';
import { calculateReport, ReportSummary } from '../services/reportEngine';
import { formatBac } from '../utils/telemetry';

interface ReportsProps { readings: TelemetryReading[]; healthReading?: TelemetryReading | null; language: Language; isLoading: boolean; error?: string | null; }
type ReportRange = 'today' | '7d' | '30d' | 'custom';
type MetricStats = { latest: number | null; average: number | null; min: number | null; max: number | null };
const stats = (readings: TelemetryReading[], key: keyof TelemetryReading): MetricStats => { const values = readings.map((reading) => reading[key]).filter((item): item is number => typeof item === 'number' && Number.isFinite(item)); return { latest: values.at(-1) ?? null, average: values.length ? values.reduce((sum, item) => sum + item, 0) / values.length : null, min: values.length ? Math.min(...values) : null, max: values.length ? Math.max(...values) : null }; };
const show = (number: number | null, suffix = '') => number === null ? 'Not available' : `${number.toFixed(number < 10 ? 3 : 1)}${suffix}`;
const Metric: React.FC<{ title: string; icon: React.ReactNode; data: MetricStats; suffix?: string }> = ({ title, icon, data, suffix = '' }) => <article className="rounded-[20px] border border-white/10 bg-white/[0.05] p-4 space-y-3"><div className="flex items-center gap-2 text-xs font-mono uppercase text-white/55">{icon}{title}</div><div className="text-2xl font-semibold text-white">{show(data.latest, suffix)}</div><div className="grid grid-cols-3 gap-2 text-[11px] font-mono text-white/45"><span>Avg {show(data.average, suffix)}</span><span>Min {show(data.min, suffix)}</span><span>Max {show(data.max, suffix)}</span></div></article>;

export const ReportsView: React.FC<ReportsProps> = ({ readings, healthReading, language, isLoading, error }) => {
  const t = translations[language] || translations.en;
  const [range, setRange] = useState<ReportRange>('7d');
  const [customStart, setCustomStart] = useState('');
  const [customEnd, setCustomEnd] = useState('');
  const now = Date.now();
  const bounds = useMemo(() => { if (range === 'today') { const start = new Date(); start.setHours(0, 0, 0, 0); return { start: start.getTime(), end: now + 1 }; } if (range === '30d') return { start: now - 30 * 86400000, end: now + 1 }; if (range === 'custom' && customStart) return { start: new Date(`${customStart}T00:00:00`).getTime(), end: customEnd ? new Date(`${customEnd}T23:59:59`).getTime() : now + 1 }; return { start: now - 7 * 86400000, end: now + 1 }; }, [range, customStart, customEnd, now]);
  const report: ReportSummary = useMemo(() => calculateReport(readings, bounds.start, bounds.end), [readings, bounds]);
  const ordered = useMemo(() => [...report.readings].sort((a, b) => a.timestamp - b.timestamp), [report.readings]);
  const bac = stats(ordered, 'alcoholBac'); const heart = stats(ordered, 'heartRateBpm'); const spo2 = stats(ordered, 'spo2Percent'); const temperature = stats(ordered, 'tempCelsius');
  const latest = healthReading || ordered.at(-1);
  const ranges = { today: t.reportToday || 'Today', '7d': t.reportLast7Days || 'Last 7 Days', '30d': t.reportLast30Days || 'Last 30 Days', custom: t.reportCustomRange || 'Custom Range' };
  if (isLoading && readings.length === 0) return <section className="max-w-6xl mx-auto px-4 py-8"><LoadingState label={t.loadingReport || 'Loading report...'} /></section>;
  return <section className="w-full max-w-6xl mx-auto px-4 sm:px-6 py-8 pb-28 space-y-6">
    <header className="flex justify-between"><div><div className="text-[10px] font-mono uppercase tracking-[0.25em] text-[#D4AF37]">{t.reportIntelligence || 'SoberWatch Intelligence'}</div><h2 className="font-luxury text-3xl font-bold text-white">{t.reportsTitle || 'Reports'}</h2><p className="text-sm text-white/50">{t.reportsSubtitle || 'Measured safety and wellness patterns'}</p></div><BarChart3 className="w-8 h-8 text-[#D4AF37]" /></header>
    {error && <div className="rounded-[18px] border border-red-500/30 bg-red-950/30 p-4 flex gap-3 text-xs text-red-200"><AlertCircle className="w-5 h-5" />{error}</div>}
    <div className="rounded-[20px] border border-[#D4AF37]/20 bg-black/30 p-4"><div className="flex items-center gap-3"><CalendarDays className="w-5 h-5 text-[#D4AF37]" /><div className="flex gap-2 overflow-x-auto">{(Object.keys(ranges) as ReportRange[]).map((item) => <button key={item} onClick={() => setRange(item)} className={`px-3 py-2 rounded-xl border text-xs font-mono whitespace-nowrap ${range === item ? 'bg-[#D4AF37] text-black border-[#D4AF37]' : 'bg-white/5 text-white/65 border-white/10'}`}>{ranges[item]}</button>)}</div></div>{range === 'custom' && <div className="flex gap-2 mt-3"><input aria-label="Start date" type="date" value={customStart} onChange={(event) => setCustomStart(event.target.value)} className="rounded-lg bg-white/10 border border-white/10 px-2 py-2 text-xs text-white" /><input aria-label="End date" type="date" value={customEnd} onChange={(event) => setCustomEnd(event.target.value)} className="rounded-lg bg-white/10 border border-white/10 px-2 py-2 text-xs text-white" /></div>}</div>
    <div className="text-xs font-mono text-white/40">{new Date(bounds.start).toLocaleDateString()} - {new Date(bounds.end).toLocaleDateString()} · {report.readings.length} {t.reportReadings || 'readings'}</div>
    {report.readings.length === 0 ? <div className="rounded-[22px] border border-white/10 bg-white/[0.04] p-12 text-center"><Database className="w-10 h-10 text-[#D4AF37] mx-auto mb-3" /><h3 className="text-white font-semibold">{t.insufficientData || 'Not enough recorded data'}</h3><p className="text-sm text-white/50 mt-2">{t.noReportReadings || 'Record more telemetry to generate a report for this period.'}</p></div> : <>
      <div className="grid lg:grid-cols-[1.2fr_2fr] gap-4"><article className="rounded-[22px] border border-[#D4AF37]/30 bg-gradient-to-br from-[#D4AF37]/15 to-white/[0.03] p-6"><div className="flex gap-2 text-[#D4AF37] font-semibold"><Gauge className="w-5 h-5" />{t.reportSafetyScore || 'Overall Safety Score'}</div><div className="text-5xl font-luxury text-white mt-4">{report.score === null ? 'Not available' : `${report.score}/100`}</div><p className="text-xs text-white/50 mt-4">{t.reportScoreBasis || 'Based on measured status, BAC, health observations, and data coverage. This is not a medical diagnosis.'}</p><div className="mt-4 space-y-1 text-xs text-white/65">{report.scoreFactors.map((factor) => <div key={factor}>• {factor}</div>)}{report.positiveFactors.map((factor) => <div key={factor} className="text-emerald-300">+ {factor}</div>)}</div></article><article className="rounded-[22px] border border-white/10 bg-white/[0.04] p-6"><div className="flex gap-2 text-white font-semibold"><Brain className="w-5 h-5 text-[#D4AF37]" />{t.reportExecutiveSummary || 'Executive Summary'}</div><p className="text-sm text-white/75 mt-4">{report.safePeriods} {t.reportSafePeriods || 'lower-risk readings'} and {report.riskPeriods} {t.reportRiskPeriods || 'elevated-risk readings'} were recorded. {report.trend === 'up' ? (t.reportTrendUp || 'BAC moved upward.') : report.trend === 'down' ? (t.reportTrendDown || 'BAC moved downward.') : (t.reportTrendStable || 'BAC remained broadly stable or needs more data.')}</p><div className="mt-4 text-sm text-white">{t.reportLatest || 'Latest'}: {formatBac(bac.latest)} · {t.reportTrend || 'Trend'}: {report.trend}</div></article></div>
      <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-3"><Metric title={t.reportBac || 'BAC'} icon={<Activity className="w-4 h-4 text-[#D4AF37]" />} data={bac} suffix=" %" /><Metric title={t.reportHeartRate || 'Heart rate'} icon={<HeartPulse className="w-4 h-4 text-rose-300" />} data={heart} suffix=" BPM" /><Metric title={t.reportSpo2 || 'SpO2'} icon={<ShieldCheck className="w-4 h-4 text-cyan-300" />} data={spo2} suffix=" %" /><Metric title={t.reportTemperature || 'Temperature'} icon={<Thermometer className="w-4 h-4 text-amber-300" />} data={temperature} suffix=" °C" /></div>
      <div className="grid lg:grid-cols-[2fr_1fr] gap-4"><article className="rounded-[22px] border border-white/10 bg-white/[0.04] p-5"><div className="flex gap-2 text-white font-semibold"><BarChart3 className="w-4 h-4 text-[#D4AF37]" />{t.reportHistoricalTrends || 'Historical Trends'}</div><div className="mt-5 h-48 flex items-end gap-1 border-b border-white/10">{ordered.map((reading) => { const readingBac = typeof reading.alcoholBac === 'number' ? reading.alcoholBac : 0; return <div key={`${reading.id || reading.timestamp}-${reading.timestamp}`} title={`${formatBac(reading.alcoholBac)} · ${new Date(reading.timestamp).toLocaleString()}`} className={`flex-1 min-w-[3px] rounded-t-sm ${reading.status === 'DANGER' ? 'bg-red-400' : reading.status === 'CAUTION' ? 'bg-amber-300' : 'bg-emerald-400'}`} style={{ height: `${Math.min(100, Math.max(4, readingBac * 900))}%` }} />; })}</div></article><article className="rounded-[22px] border border-white/10 bg-white/[0.04] p-5 space-y-3"><div className="flex gap-2 text-white font-semibold"><Database className="w-4 h-4 text-[#D4AF37]" />{t.reportDataQuality || 'Data Quality & Device'}</div><div className="text-sm text-white/70">{t.reportReadings || 'Readings'}: <strong className="text-white">{report.readings.length}</strong></div><div className="text-sm text-white/70">{t.reportDevice || 'Device'}: <strong className="text-white">{report.devices.length ? report.devices.join(', ') : 'Not available'}</strong></div><div className="text-sm text-white/70">{t.reportCoverage || 'Coverage'}: <strong className="text-white">{show(report.dataQuality, '%')}</strong></div><div className="text-xs text-white/40">{latest?.source || (t.reportSourceUnavailable || 'Sensor source not available')}</div></article></div>
      <article className="rounded-[22px] border border-white/10 bg-white/[0.04] p-5"><div className="flex gap-2 text-white font-semibold"><CheckCircle2 className="w-4 h-4 text-emerald-300" />{t.reportRecommendations || 'Recommendations'}</div><div className="grid md:grid-cols-2 gap-3 mt-4">{report.recommendations.map((item) => <div key={item.observation} className="border-l-2 border-[#D4AF37] pl-3 text-xs space-y-1"><div className="font-semibold text-white">{item.observation}</div><div className="text-white/55"><strong>{t.reportWhy || 'Why'}:</strong> {item.why}</div><div className="text-white/70"><strong>{t.reportAction || 'Action'}:</strong> {item.action}</div><div className="uppercase text-[10px] text-[#D4AF37]">{t.reportPriority || 'Priority'}: {item.priority}</div></div>)}</div></article>
      <article className="rounded-[22px] border border-[#D4AF37]/20 bg-[#D4AF37]/[0.05] p-5"><div className="text-[#D4AF37] font-semibold">{t.reportFinancialImpact || 'Financial Impact'}</div><p className="text-sm text-white/60 mt-3">{t.reportFinancialUnavailable || 'Not available. No configured fuel, usage, downtime, or maintenance assumptions are present, so no financial amount is estimated.'}</p><p className="text-[11px] text-white/35 mt-2">{t.reportEstimatedNotice || 'Future amounts will be labeled Estimated and based only on configured assumptions and recorded data.'}</p></article>
    </>}
  </section>;
};
